### ISSUE TITLE
Are you aware of gdbm?

### ISSUE THREAD

**Issue by Earnestly** [Becavalier/SHDB#2]
`gdbm` is part of [GNU](http://www.gnu.org.ua/software/gdbm/), based on the old unix [dbm](https://en.wikipedia.org/wiki/Dbm) and fairly  available.

Although it would make more sense to write a simple C (or whichever language of choice (even [bash](https://github.com/taviso/ctypes.sh) :-P)) program which exposes operations on gdbm databases in a more shell friendly manner. _(`gdbmtool` itself is here http://git.gnu.org.ua/cgit/gdbm.git/tree/src/gdbmtool.c)_

Not an issue, but hopefully some new information. 

_PS: Here's some example usage from a rudimentary wrapper based on `gdbmtool` I quickly threw together, almost all of this functionality came for free:_

``` sh
% ./gdbm foo.db set key value
% ./gdbm foo.db ls
key value
% ./gdbm foo.db count
1
% ./gdbm foo.db get key
value
% ./gdbm foo.db del key
% ./gdbm foo.db count
0

# Here I simply piggyback on the shells natural return
# value allowing me to use this command cleanly in if 
# statements, for example:
# 
#  if ! gdbm "$db" isset "$key"; then
#      printf 'No %s in %s\n' "$key" "$db"
#      exit 1
#  fi

% ./gdbm foo.db isset nonextant
zsh: exit 1     ./gdbm foo.db isset nonextant
```

**Comment by Becavalier** [comment]
Hi Earnestly,
Thanks for your advice, it's really the first time that I heard about "gdbm", but it really can help me extend and optimize the ability of SHDB.

Actually, the role of SHDB is ambiguous, for the most of time, it is just a hobby and just an open source project for shell learning.

Maybe as you said, I can rewrite SHDB with pure c language, and this will increase its portability in most of the cases.

Anyway, thanks for your opinion and I will keep on optimizing SHDB with your advice.

**Comment by Becavalier** [comment]
Maybe we can integrated a small gdbm client written in c into SHDB, I think that would be more interesting :-P

**Comment by Earnestly** [comment]
Oh yeah, at least it's what I'd do and gdbm seems to be a nice solution (although I'm not familiar with its limits or the C API) just because it seems fairly widely available and pretty small.

My fairly bad script wrapper around `gdbmtool` is included below with some comments on the initial issues I encountered.  It may in the end not be the right library (or tool) to use for your project, but the purpose of this issue was just to share some of the things I found which might be helpful.

PS: Here's an example tool someone did in ruby: http://unix.stackexchange.com/a/216783

Alternatively to gdbm there is also [DJB's cdb](http://cr.yp.to/cdb.html) and the various implementations (e.g. [TinyCDB](http://www.corpit.ru/mjt/tinycdb.html)) of it apart from his and his `cdbget` tool (no delete).

``` sh
#!/bin/bash
# gdbm - stupid wrapper around gdbmtool for basic db management

if [[ $1 = -h ]] || (($# == 0)); then
    printf 'usage: gdbm database operation [key] [value [value] ...]\n' >&2
    exit
fi

db=$1
op=$2
k=$3
v=(${@:4})

# Both isset and count functions are unnecessarily ugly because gdbmtool isn't
# very accomodating on the shell, such as no meaningful exit code, ready
# made commands for boolean tests, or command-line interface for accepting
# commands.

# Making a simple tool exposing the much richer gdbm C API could improve this
# interaction while making it more robust.

gdbm() {
    # -s requires a sync after every write.  We get locking on the db for free
    # as well.
    gdbmtool -s "$db" 2>&1
}

case $op in
    ls)  gdbm <<< 'list' ;;
    set) gdbm <<< "store $k ${v[*]}" ;;
    get) gdbm <<< "fetch $k" ;;
    del) gdbm <<< "delete $k" ;;

    isset) ! gdbm <<< "fetch $k" | grep -q 'No such item found.' ;;
    count) gdbm <<< 'count' | awk '{print $3}' ;;
esac
```
